version: "3.9"

services:

  ecom_backend:
    build: .
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      DSN: "host=postgres user=user password=user dbname=ecom_db port=5432 sslmode=disable"
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: "ecom_db"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "user"
    ports:
      - "5440:5432"
    volumes:
      - pg_vol:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "ecom_db" ]
      interval: 5s
      timeout: 5s
      retries: 10


volumes:
  pg_vol: